### ISSUE TITLE
Origin Story

### ISSUE THREAD

**Issue by d4rken** [d4rken/mystic-permissions#1]
By @TheMysticS from d4rken/sdmaid-public#5609

> The idea I spoke about earlier is about an app that will list all app permissions in one place. Currently, Android shows app permissions in 3 different places:
> 
> App Info page
> Special Access
> Permissions Manager
> In order to control or just see what permissions an app has access to, the user has to go to 3 different places now.
> 
> This new app I'm suggesting will basically list every single permission an app has requested in one place, giving the user a bird's eye view of app permissions.
> 
> It will have two tabs at the bottom (or top):
> 
> Apps: This will list all the apps installed. Clicking on any app will list every single permission that the app has requested, including those that show up under Permissions Manager and Special Access, along with their status (ON/ OFF, Allowed/ Disallowed, etc.)
> 
> Permissions: This will list every single permission such as Contacts, Microphone, Camera, etc., including those that show up under Permissions Manager and Special Access. Clicking on each will show all the apps that currently has access to that permission.
> 
> This will also include internet permissions, SharedUserID status!
> 
> In both the above cases, it will be nice to segregate the output in two sections: One where apps have been allowed a permission or permissions that an app currently has access to, and another section where the same is denied.
> 
> Due to limitations of Android, this app will not allow for controlling permissions from within the app, atleast not without root. Instead, it will provide a bird's eye view of the entire permission set available to each app, and also provide a shortcut to the appropriate System Settings page, if the user wants to change any.
> 
> Currently, there is not a single app that can do this. So you may consider making one.
> 
> Thanks.

**Comment by dragonGod97677** [comment]
Speaking SharedUserID, it should have a separate tab and sort apps that have same SharedUserID

**Comment by d4rken** [comment]
> Speaking SharedUserID, it should have a separate tab and sort apps that have same SharedUserID

Not sure how that would look UI wise, so it's 3 tabs?

* Apps
* Permissions
* ?SharedUserId?

**Comment by dragonGod97677** [comment]
> > Speaking SharedUserID, it should have a separate tab and sort apps that have same SharedUserID
> 
> Not sure how that would look UI wise, so it's 3 tabs?
> 
> * Apps
> * Permissions
> * ?SharedUserId?

Yes 3 tabs and sort like this but by id
![Screenshot_2022-07-14-03-13-45-61](https://user-images.githubusercontent.com/38875906/178813360-99ed5ae3-b3c4-43f1-84da-f46b8d4026c2.png)
But text only, when the user taps a id, it will show a drop down list of apps have the shared id

**Comment by TheMysticS** [comment]
On the Apps tab where all apps are listed, a label (similar to the ones used in SD Maid) indicating SharedUserID should be fine. 

Clicking on the label should list all the other apps in a small pop-up window that have the same SharedUserID.

Clicking on the app should list every single permission requested by the app, with filters to see the ones allowed and those that are disallowed.

I'm not sure if a separate tab is required.

**Comment by dragonGod97677** [comment]
> I'm not sure if a separate tab is required.

Having a tabs can sort it.

for your suggestion 

> On the Apps tab where all apps are listed, a label (similar to the ones used in SD Maid) indicating SharedUserID should be fine.

Why not both?

**Comment by TheMysticS** [comment]
> > I'm not sure if a separate tab is required.
> 
> Having a tabs can sort it.
> 
> for your suggestion
> 
> > On the Apps tab where all apps are listed, a label (similar to the ones used in SD Maid) indicating SharedUserID should be fine.
> 
> Why not both?

I will admit I don't fully understand the SharedUserID feature. Is this something that many apps use? As far as I understood, this SharedUserID is limited to apps from the same developer, isn't it?

If not many apps have this, then a separate tab may be unnecessary to keep the UI simple and clean.

**Comment by dragonGod97677** [comment]
> 

You got a point, shared id is rare can can mostly found used in system apps.
The only downloadable app on play store that uses shared id is Automate

**Comment by d4rken** [comment]
So far:

![Screenshot from 2022-07-14 00-56-41](https://user-images.githubusercontent.com/1439229/178850961-2020e3e9-8c60-4582-855d-67b762d70f3f.png)

**Comment by dragonGod97677** [comment]
> So far:
> 
> ![Screenshot from 2022-07-14 00-56-41](https://user-images.githubusercontent.com/1439229/178850961-2020e3e9-8c60-4582-855d-67b762d70f3f.png)

Add dark theme

**Comment by d4rken** [comment]
Lol, do you mean "Could you also add a dark theme, please?" :thinking: 

It will pick a theme based on your system setting.

Colors are defined here, feel free to tweak them, there is a tool to generate themes here:
https://material-foundation.github.io/material-theme-builder/

**Comment by d4rken** [comment]
Not sure how much info is needed in the overview:

![Screenshot from 2022-07-14 01-44-36](https://user-images.githubusercontent.com/1439229/178855568-2f429c6f-f799-4a23-8f90-45619d98c9f4.png)

**Comment by dragonGod97677** [comment]
> Lol, do you mean "Could you also add a dark theme, please?" 🤔
> 
> It will pick a theme based on your system setting.
> 
> Colors are defined here, feel free to tweak them, there is a tool to generate themes here: https://material-foundation.github.io/material-theme-builder/

Edited my last comment and users can import their own theme?

**Comment by d4rken** [comment]
No this is a code change. You and @TheMysticS could contribute more than just discussions if you want :slightly_smiling_face:.

The generated files contain a color set which can replace the current one:
https://github.com/d4rken/mystic-permissions/blob/main/app/src/main/res/values/colors.xml

The purple color scheme is not super nice, it's just the default of another project of mine (https://github.com/d4rken/android-starter-v4).

**Comment by d4rken** [comment]
Automatic builds are now working:
https://github.com/d4rken/mystic-permissions/releases

Time for :sleeping:

**Comment by dragonGod97677** [comment]
> Automatic builds are now working: https://github.com/d4rken/mystic-permissions/releases
> 
> Time for 😴

Good night

**Comment by dragonGod97677** [comment]
> No this is a code change. You and @TheMysticS could contribute more than just discussions if you want 🙂.
> 
> The generated files contain a color set which can replace the current one: https://github.com/d4rken/mystic-permissions/blob/main/app/src/main/res/values/colors.xml
> 
> The purple color scheme is not super nice, it's just the default of another project of mine (https://github.com/d4rken/android-starter-v4).

Okay!

**Comment by TheMysticS** [comment]
> Automatic builds are now working: https://github.com/d4rken/mystic-permissions/releases
> 
> Time for 😴

That was superfast. 😍😍

The Permissions tab can be simplified, by listing them using the same name as in System Settings:

![Screenshot_20220714-075808](https://user-images.githubusercontent.com/54448474/178886014-ed018314-18d9-4692-83f2-1cc7a1455c09.png)


Descriptions can be shown once an item is clicked. 

Anyways, we can discuss these after a good night's sleep. I'll go through your links and help you in whatever way I can.

Thanks very much.

Goodnight.

**Comment by TheMysticS** [comment]
Under Android System Settings, we only see about 30 permissions. The permissions tab has literally well over a hundred permissions, and many of these towards the end haven't been granted to any app.

Are these other permissions not modifiable? If so, can we have some filters for this section:

🔲 All Apps
🔲 User Apps
🔲 System Apps

🔲 Include non-modifiable permissions

**Comment by TheMysticS** [comment]
> > > Speaking SharedUserID, it should have a separate tab and sort apps that have same SharedUserID
> > 
> > 
> > Not sure how that would look UI wise, so it's 3 tabs?
> > 
> > * Apps
> > * Permissions
> > * ?SharedUserId?
> 
> Yes 3 tabs and sort like this but by id ![Screenshot_2022-07-14-03-13-45-61](https://user-images.githubusercontent.com/38875906/178813360-99ed5ae3-b3c4-43f1-84da-f46b8d4026c2.png) But text only, when the user taps a id, it will show a drop down list of apps have the shared id

Which app is this?

**Comment by TheMysticS** [comment]
> No this is a code change. You and @TheMysticS could contribute more than just discussions if you want 🙂.
> 
> The generated files contain a color set which can replace the current one: https://github.com/d4rken/mystic-permissions/blob/main/app/src/main/res/values/colors.xml
> 
> The purple color scheme is not super nice, it's just the default of another project of mine (https://github.com/d4rken/android-starter-v4).

I have proposed just one change to the primary colour: from the existing one to #002121. Is it possible to make these changes within the app and see how it looks?

**Comment by dragonGod97677** [comment]
> > No this is a code change. You and @TheMysticS could contribute more than just discussions if you want 🙂.
> > The generated files contain a color set which can replace the current one: https://github.com/d4rken/mystic-permissions/blob/main/app/src/main/res/values/colors.xml
> > The purple color scheme is not super nice, it's just the default of another project of mine (https://github.com/d4rken/android-starter-v4).
> 
> I have proposed just one change to the primary colour: from the existing one to #002121. Is it possible to make these changes within the app and see how it looks?

Im gonna make a pull request for it

**Comment by dragonGod97677** [comment]
Oh wait i think i can build it, hold on

**Comment by dragonGod97677** [comment]
Aaaand it throws me an error

**Comment by dragonGod97677** [comment]
Hey @d4rken how do i gonna fix this error ``SigningConfig "release" is missing required property "storeFile".``

**Comment by TheMysticS** [comment]
> Hey @d4rken how do i gonna fix this error `SigningConfig "release" is missing required property "storeFile".`

What did you do? Modify the apk?

**Comment by TheMysticS** [comment]
I have prepared a layout of how the screen will look like when someone clicks on an app to see all the permissions:

<img width="368" alt="Screenshot 2022-07-14 at 15 05 01" src="https://user-images.githubusercontent.com/54448474/178952647-1a88182f-52d5-468c-95e6-fa2a82fb85e0.png">

Do you like it?

**Comment by d4rken** [comment]
> Hey @d4rken how do i gonna fix this error `SigningConfig "release" is missing required property "storeFile".`

When opening the project in Android Studio, set the buildVariant to "debug", then you should be able to modify the app and install it. In the `release` variant it will try to sign the APK and you don't have the keystore with the signature.

![Screenshot from 2022-07-14 12-06-41](https://user-images.githubusercontent.com/1439229/178958383-f5f5db94-6b8e-45c9-ae8b-9d40ebea85b0.png)

> I have prepared a layout of how the screen will look like when someone clicks on an app to see all the permissions:
> 
> [Screenshot 2022-07-14 at 15 15 17](https://user-images.githubusercontent.com/54448474/178954295-65959bb2-62ed-4377-b25e-d735427f6c94.png)
> 
> Do you like it?
> 
> The items may be reclassified to a different risk category if the current classification is not correct.
> 
> Each of the permission above is actually a direct link to System Settings for that app, so user can modify the permission, as necessary.

Nice mockup! Some thoughts:
* This looks a bit like a desktop UI though, difficult fit on a mobile device :sweat_smile:.
* I'm not sure we should classify them by "risk", I always hated that about other apps. "Risk" is subjective. also all "high risk" permissions without the app having internet are actually risky  right?
* Not every permission has "read+write" variants, for most it's just a single permission. Let's not waste a whole column for every permission on it.
* I agree that there are many permissions that are not that interesting to the user and we should hide/collapse them. Is there a way to do it dynamically without having to classify them by hand? Maybe the most common permissions among all non-system apps?
* You list "Body sensors" is that on purpose, are you referring to "permission groups", a permission may belong to a group, we could show that in the details too. I'm uncertain if we should actually group them by it though as they more of an internal detail that isn't really useful. These are the groups on my device:

```
com.felicanetworks.mfc.permission.group.FELICA_GROUP
com.google.android.gms.permission.CAR_INFORMATION
android.permission-group.CONTACTS
android.permission-group.PHONE
android.permission-group.CALENDAR
android.permission-group.CALL_LOG
android.permission-group.CAMERA
android.permission-group.UNDEFINED
android.permission-group.ACTIVITY_RECOGNITION
android.permission-group.SENSORS
android.permission-group.LOCATION
android.permission-group.STORAGE
android.permission-group.MICROPHONE
android.permission-group.NEARBY_DEVICES
android.permission-group.SMS
null
```
Many just belong to the `null` group.

**Comment by dragonGod97677** [comment]
> When opening the project in Android Studio, set the buildVariant to "debug", then you should be able to modify the app and install it. In the `release` variant it will try to sign the APK and you don't have the keystore with the signature.
> 
> ![Screenshot from 2022-07-14 12-06-41](https://user-images.githubusercontent.com/1439229/178958383-f5f5db94-6b8e-45c9-ae8b-9d40ebea85b0.png)

Uh, i did the build using this 
![Screenshot_2022-07-14-18-38-25-83](https://user-images.githubusercontent.com/38875906/178964350-fef7b4fa-442d-43ab-9b2e-df84b620cd2f.png)

**Comment by TheMysticS** [comment]
> > Hey @d4rken how do i gonna fix this error `SigningConfig "release" is missing required property "storeFile".`
> 
> When opening the project in Android Studio, set the buildVariant to "debug", then you should be able to modify the app and install it. In the `release` variant it will try to sign the APK and you don't have the keystore with the signature.
> 
> ![Screenshot from 2022-07-14 12-06-41](https://user-images.githubusercontent.com/1439229/178958383-f5f5db94-6b8e-45c9-ae8b-9d40ebea85b0.png)
> 
> > I have prepared a layout of how the screen will look like when someone clicks on an app to see all the permissions:
> > [Screenshot 2022-07-14 at 15 15 17](https://user-images.githubusercontent.com/54448474/178954295-65959bb2-62ed-4377-b25e-d735427f6c94.png)
> > Do you like it?
> > The items may be reclassified to a different risk category if the current classification is not correct.
> > Each of the permission above is actually a direct link to System Settings for that app, so user can modify the permission, as necessary.
> 
> Nice mockup! Some thoughts:
> 
> * This looks a bit like a desktop UI though, difficult fit on a mobile device 😅.
> * I'm not sure we should classify them by "risk", I always hated that about other apps. "Risk" is subjective. also all "high risk" permissions without the app having internet are actually risky  right?
> * Not every permission has "read+write" variants, for most it's just a single permission. Let's not waste a whole column for every permission on it.
> * I agree that there are many permissions that are not that interesting to the user and we should hide/collapse them. Is there a way to do it dynamically without having to classify them by hand? Maybe the most common permissions among all non-system apps?
> * You list "Body sensors" is that on purpose, are you referring to "permission groups", a permission may belong to a group, we could show that in the details too. I'm uncertain if we should actually group them by it though as they more of an internal detail that isn't really useful. These are the groups on my device:
> 
> ```
> com.felicanetworks.mfc.permission.group.FELICA_GROUP
> com.google.android.gms.permission.CAR_INFORMATION
> android.permission-group.CONTACTS
> android.permission-group.PHONE
> android.permission-group.CALENDAR
> android.permission-group.CALL_LOG
> android.permission-group.CAMERA
> android.permission-group.UNDEFINED
> android.permission-group.ACTIVITY_RECOGNITION
> android.permission-group.SENSORS
> android.permission-group.LOCATION
> android.permission-group.STORAGE
> android.permission-group.MICROPHONE
> android.permission-group.NEARBY_DEVICES
> android.permission-group.SMS
> null
> ```
> 
> Many just belong to the `null` group.

I have modified it a bit more to also show the App Status on Top (from App Control of SD Maid). Check it out.

The categories and read/ write status are stuff I picked up from existing permission manager apps. If you think it won't fit well into mobile screens, feel free to modify it as you please. The idea is only about presenting all info in one place, preferably without having to scroll.

Access to camera, microphone, etc. are indeed high risk permissions. But for apps like WhatsApp or other video calling apps, these become necessary permissions. Same is true for audio recording apps, Banking apps, and a few others. So while the permissions themselves are classified as high risk, the apps cannot be due to the functions they perform. I'll leave that to your best judgement.

The table lists all the permissions that users can actually modify from System Settings.  This includes 'Body Sensors', so I included it. It is not about user interest. I consider myself as an above-average 'user', and the number of permissions that showed up in your app is indeed overwhelming. And if many of those permissions are beyond user control, it is best to leave them in collapsed form for advanced users to see.

**Comment by d4rken** [comment]
I'll cook something up for the next release.
What do we show when pressing on an entry in the permissions list?

>preferably without having to scroll.

There are too many screen sizes, and too much information. Scroll will be there, must be there...

@dragonGod97677 I'd be impressed if you could get that to work more easily then just downloading AS and opening the project in it :sweat_smile:

**Comment by TheMysticS** [comment]
> I'll cook something up for the next release. What do we show when pressing on an entry in the permissions list?
> 
> > preferably without having to scroll.
> 
> There are too many screen sizes, and too much information. Scroll will be there, must be there...
> 
> @dragonGod97677 I'd be impressed if you could get that to work more easily then just downloading AS and opening the project in it 😅

Clicking on a permission will take the user to the corresponding System Settings screen for that app.

**Comment by d4rken** [comment]
> Clicking on a permission will take the user to the corresponding System Settings screen for that app.

When going AppList > App > Permission
But what about PermissionList > Permission?

**Comment by TheMysticS** [comment]
> > Clicking on a permission will take the user to the corresponding System Settings screen for that app.
> 
> When going AppList > App > Permission But what about PermissionList > Permission?

Under Permission List/ Permission, we'll see the list of apps allowed/ having access to that permission. If user clicks on any app, it will take him to that permission setting for that app under System Settings.

**Comment by TheMysticS** [comment]
Also, clicking on SharedUserID should list all the other apps that are using the same ID.

**Comment by dragonGod97677** [comment]
> I'll cook something up for the next release. What do we show when pressing on an entry in the permissions list?
> 
> > preferably without having to scroll.
> 
> There are too many screen sizes, and too much information. Scroll will be there, must be there...
> 
> @dragonGod97677 I'd be impressed if you could get that to work more easily then just downloading AS and opening the project in it 😅

There's a problem, i dont have a pc 😅

**Comment by TheMysticS** [comment]
> Which app is this?
>
> https://play.google.com/store/apps/details?id=com.libin.notification
Okay, but aren't you already on Android 12 which supports Notification History?

**Comment by dragonGod97677** [comment]
> > Which app is this?
> > https://play.google.com/store/apps/details?id=com.libin.notification
> 
> Okay, but aren't you already on Android 12 which supports Notification History?

Uh no my phone is android 8 (old right?)

**Comment by TheMysticS** [comment]
> I just use what ever available app that i can use
>
That's good to know. I'm assuming you also have a background in IT. I do a lot of tinkering myself, but never tried these things.

**Comment by dragonGod97677** [comment]
Hey @TheMysticS what is your design thought for Permission tab?
Im suggesting the design for it will be like this but material look of course 
![Screenshot_2022-07-14-20-49-55-16](https://user-images.githubusercontent.com/38875906/178986694-b5cabee7-1b27-446a-8d94-dcc93d869ed0.png)


And for other remaining permission that regular user won't be touching anyway will be in additional permissions

**Comment by dragonGod97677** [comment]
We need this app to be noob friendly

**Comment by dragonGod97677** [comment]
> For off-topic use Discord ( you are both on there 😉), otherwise this issue becomes more chaos than it already is 😁 !
> 
> v0.0.2 is currently building, navigation to details works and shows a little info already: https://github.com/d4rken/mystic-permissions/actions/runs/2670433457

Okay and nice, v 0.0.2, i cant wait for it to finished building

**Comment by TheMysticS** [comment]
> Hey @TheMysticS what is your design thought for Permission tab? Im suggesting the design for it will be like this but material look of course ![Screenshot_2022-07-14-20-49-55-16](https://user-images.githubusercontent.com/38875906/178986694-b5cabee7-1b27-446a-8d94-dcc93d869ed0.png)
> 
> And for other remaining permission that regular user won't be touching anyway will be in additional permissions

This is the stock Android setting. I had suggested based on risk categories (hope you saw my design), but @d4rken isn't in favour of it. And that's okay as long as all those permissions (that show up in all the 3 screens mentioned in OP) show up here, and the rest of the other permissions under Additional Permissions. I have posted the screenshot from one of the existing apps here: https://github.com/d4rken/mystic-permissions/issues/1#issuecomment-1183921012

**Comment by dragonGod97677** [comment]
> This is the stock Android setting.
I know i just used it as sample

> I had suggested based on risk categories (hope you saw my design), but @d4rken isn't in favour of it. And that's okay as long as all those permissions (that show up in all the 3 screens mentioned in OP) show up here, and the rest of the other permissions under Additional Permissions. I have posted the screenshot from one of the existing apps here: [#1 (comment)](https://github.com/d4rken/mystic-permissions/issues/1#issuecomment-1183921012)

Ah yeah seen it, and okay

**Comment by TheMysticS** [comment]
Can we have a 3rd tab for this that provides a summary page?

The summary can include details like:

1. WiFi security: If the connected WiFi is insecure
2. No. of apps with 'Install from unknown sources' permission
3. No. of apps with Device Admin permissions
4. If any app is currently using the Camera and/ or Microphone 
5. No. of user apps installed
6. No. of apps which have updates available on Google Play Store 
7. No. of 'External' apps: These are apps installed using the package manager.

Clicking on any of the above would take launch the corresponding page in System Settings.

Point No. 6

On Samsung devices (and may be other devices too), if an app is in Deep Sleep, it is de-linked from Google Play Store (temporarily), so updates don't show up until it is enabled again. It would be nice to know if updates are available for such apps.

**Comment by dragonGod97677** [comment]
This is nice but tho, this may be out of scope, the app is only for mostly
app permissions

**Comment by TheMysticS** [comment]
> This is nice but tho, this may be out of scope, the app is only for mostly app permissions
> 
More than half of them are strictly about app permissions. The rest are about having a simple **overview** of the important elements of device status. Like 'At a Glance'.

Also, there are no apps that can currently do points 6 and 7.

**Comment by d4rken** [comment]
I would prefer to keep the scope of this app narrow, so as to be able to have it actually "finished" at some point.

> WiFi security: If the connected WiFi is insecure

Out of Scope (OOS)

> No. of apps with 'Install from unknown sources' permission enabled

Is the `android.permission.REQUEST_INSTALL_PACKAGES` not already shown?

> No. of apps with Device Admin permissions enabled

Same as above, is this not already listed?

> If any app is currently using the Camera and/ or Microphone

If you mean like the green display icon on newer Pixels, when it is CURRENTLY in-use, I'd say this is OOS

> No. of user apps installed

Viable, could maybe just be a badge on the bottom bar?

> No. of apps which have updates available on Google Play Store

I don't want to add in any Google dependencies, OOS.

> No. of 'External' apps: These are apps installed using the package manager, i.e. Sideloaded Apps. Those that are neither from Google Play Store nor from OEM managed Stores like Samsung Galaxy Store, Huawei App Gallery, etc. Please note that apps installed using 3rd party App Stores like f-droid or others would still be counted as Sideloaded apps.

On the edge. How do we get the list identifiers for OEM stores, crowdsourced ? :grin:

**Comment by TheMysticS** [comment]
> I would prefer to keep the scope of this app narrow, so as to be able to have it actually "finished" at some point.
> 
Sure. No problem.

> > WiFi security: If the connected WiFi is insecure
> 
> Out of Scope (OOS)
> 
Okay!

> > No. of apps with 'Install from unknown sources' permission enabled
> 
> Is the `android.permission.REQUEST_INSTALL_PACKAGES` not already shown?
> 
> > No. of apps with Device Admin permissions enabled
> 
> Same as above, is this not already listed?
> 
Yes, the above two are already part of permissions. They are included in Summary given the nature or security implications of these permissions. I have added point 8 to include apps with Accessibility Permissions enabled too.

> > If any app is currently using the Camera and/ or Microphone
> 
> If you mean like the green display icon on newer Pixels, when it is CURRENTLY in-use, I'd say this is OOS
> 
> > No. of user apps installed
> 
> Viable, could maybe just be a badge on the bottom bar?
> 
Something simple like this would be completely fine:
**No. of user apps installed: 300.**

> > No. of apps which have updates available on Google Play Store
> 
> I don't want to add in any Google dependencies, OOS.
> 
Okay.

> > No. of 'External' apps: These are apps installed using the package manager, i.e. Sideloaded Apps. Those that are neither from Google Play Store nor from OEM managed Stores like Samsung Galaxy Store, Huawei App Gallery, etc. Please note that apps installed using 3rd party App Stores like f-droid or others would still be counted as Sideloaded apps.
> 
> On the edge. How do we get the list identifiers for OEM stores, crowdsourced ? 😁
Aren't such identifiers very few? Like just one per brand, and that too only if the brand has a Store of its own?

As far as I know, it is just Samsung, Huawei and may be Oppo/ Vivo. OnePlus doesn't have an App Store, nor does Xiaomi. And neither do Nokia or Motorola. What else is left? Not sure about Sony.

**Comment by d4rken** [comment]
> As far as I know, it is just Samsung, Huawei and may be Oppo/ Vivo. OnePlus doesn't have an App Store, nor does Xiaomi. And neither do Nokia or Motorola. What else is left? Not sure about Sony.

We need the identifiers, e.g. what SD Maid or other apps display for an app installed from that store.

**Comment by TheMysticS** [comment]
> > As far as I know, it is just Samsung, Huawei and may be Oppo/ Vivo. OnePlus doesn't have an App Store, nor does Xiaomi. And neither do Nokia or Motorola. What else is left? Not sure about Sony.
> 
> We need the identifiers, e.g. what SD Maid or other apps display for an app installed from that store.

Nothing. A label will only be shown for apps that do not come from any of the above sources.

**Comment by TheMysticS** [comment]
Check this out:

![Screenshot_20220716-185551_Settings](https://user-images.githubusercontent.com/54448474/179356851-23e3ce60-2e42-4a08-9ed6-73966e76d222.png)

This is from the App Info page of an app that came pre-installed on my Samsung Phone. It is from the Samsung Galaxy Store. There are some more apps too. Almost all of the rest show Google Play Store, and if I click on it, it will take me to the App Page in the Store.

**Comment by TheMysticS** [comment]
There is only one identifier for the Galaxy Store, isn't it?

By identifier, do you mean package name?

**Comment by d4rken** [comment]
> By identifier, do you mean package name?

Yes, e.g. for Google Play Store it is `com.android.vending`.
![Screenshot from 2022-07-16 15-30-49](https://user-images.githubusercontent.com/1439229/179357023-d6eec86f-062e-4631-8c26-b42c0cec4e41.png)

**Comment by TheMysticS** [comment]
Here is another app that I installed using an app called SAI:

![Screenshot_20220716-185915_Settings](https://user-images.githubusercontent.com/54448474/179357015-d2b377be-379c-48e4-a7da-1b117940f399.png)

So this app will have a label called 'Sideloaded' or 'External' or whatever suits best

**Comment by TheMysticS** [comment]
> > By identifier, do you mean package name?
> 
> Yes, e.g. for Google Play Store it is `com.android.vending`. ![Screenshot from 2022-07-16 15-30-49](https://user-images.githubusercontent.com/1439229/179357023-d6eec86f-062e-4631-8c26-b42c0cec4e41.png)

Which means there is only one identifier per brand. There are only a handful of brands that come with an app store. I can check the one for Samsung and let you know.

**Comment by TheMysticS** [comment]
I will just do a Google search and list the package names of the known official stores.

**Comment by TheMysticS** [comment]
Here it is (based on Google search):

Samsung: com.sec.android.app.samsungapps

Huawei: com.huawei.appmarket

From what I read, I think Oppo & Vivo use Huawei's App Gallery as an alternative to Google Play Store. They don't have a store of their own. So essentially there are only two official App Stores in addition to Google Play Store.

Apps installed from any of these Stores will not have any label for that. Only apps that have been installed using other apps will have a label.

**Comment by d4rken** [comment]
> I will just do a Google search and list the package names of the known official stores.

Can you create a new ticket to track this as new feature?
Let's keep it a bit organized :sweat_smile: , then I can also reference it in code :smile:

**Comment by TheMysticS** [comment]
> > I will just do a Google search and list the package names of the known official stores.
> 
> Can you create a new ticket to track this as new feature? Let's keep it a bit organized 😅 , then I can also reference it in code 😄

I have already done that as a new feature request for SD Maid. Do you want me to open another one?

**Comment by d4rken** [comment]
> I have already done that as a new feature request for SD Maid. Do you want me to open another one?

Yes. You can keep the information in one ticket, and link to it in the other ticket.
Data collection is 1 task, but implementing it into SD Maid and/or MysticPermissions, is two tasks :).

**Comment by TheMysticS** [comment]
Okay. We can continue discussion of this particular feature here:

https://github.com/d4rken/sdmaid-public/issues/5618

**Comment by TheMysticS** [comment]
![Screenshot_2022-07-17-07-50-45-73_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179381351-d1aa1c6e-1e8c-4ad2-9d17-3eafc7204f5d.jpg)

1. I think the yellow colour is NOT very intuitive. Grey colour would be better in my opinion (including on the permissions screen).


![Screenshot_2022-07-17-07-50-38-62_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179381373-165ec703-22b0-48be-9699-40df0eb55dec.jpg)

2. Can you add two more labels here:

     • Google Play Store
     • OEM Store (better than using actual names to save space)

3. Can you include count of each category in brackets?

4.

**Comment by TheMysticS** [comment]
I'm not sure what your plans for the Permissions tab is. 

For those 30 or so permissions that user can control via System Settings: Will you be displaying those with the same names as they appear in System Settings? And club all the others under **Additional Permissions**?

If you intend keeping the Permissions tab as it is now, then can you implement a filter bar like this:

![iMarkup_20220717_143556](https://user-images.githubusercontent.com/54448474/179391674-0164f1e1-44aa-4739-a52c-3938e74ffd7c.png)

Here, the icons will all be of the same colour (green is fine). Tapping on any of them will list all apps which have that permission enabled. This bar will be scrollable horizontally to accomodate the remaining permissions not visible currently.

**Comment by TheMysticS** [comment]
Internet icon should look somewhat like this:

![Internet](https://user-images.githubusercontent.com/54448474/179391864-9ee15e6b-fd99-4f60-b156-5c5bf64fc81c.jpg)

**Comment by d4rken** [comment]
Please open new issue tickets for separate ideas (don't forget to reference the version you are testing on).

I'm getting confused by this one :laughing:
