### ISSUE TITLE
SharedUserID status

### ISSUE THREAD

**Issue by TheMysticS** [d4rken/mystic-permissions#21]
Please add the SharedUserID status for apps.

The same should also reflect in the icon indicators.

For example, the SD Maid unlocker has no internet icon, but it should ideally show the internet icon with an orange colour, since the main SD Maid app has internet access.

![Screenshot_2022-07-17-20-19-52-60_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179403960-f2226f65-ab01-49aa-9d64-b95e68fdada3.jpg)

**Comment by d4rken** [comment]
SD Maid + Unlocker does not have a shared user id.
 There two have a shared ID:
![Screenshot from 2022-07-17 17-06-54](https://user-images.githubusercontent.com/1439229/179404466-6861bda3-a6b9-477c-b7d2-45a2b980a062.png)

**Comment by TheMysticS** [comment]
> SD Maid + Unlocker does not have a shared user id. There two have a shared ID: ![Screenshot from 2022-07-17 17-06-54](https://user-images.githubusercontent.com/1439229/179404466-6861bda3-a6b9-477c-b7d2-45a2b980a062.png)

Okay. So is the exclamation ❗ mark supposed to mean that the app can still connect to internet using SharedUserID, even though it by itself has no internet permissions of its own?

I'm assuming that if the main Poweramp player is uninstalled, then the Pro key will not show any icon.

**Comment by d4rken** [comment]
> I'm assuming that if the main Poweramp player is uninstalled, then the Pro key will not show any icon.

Correct.

Maybe we can later add a different message when clicking on the icon.

**Comment by TheMysticS** [comment]
> Maybe we can later add a different message when clicking on the icon.
>
Exclamation ❗ mark can be misinterpreted as an error. I think it would be better to change the colour of that icon to yellow or orange, same as used in SD Maid.

Also, it would be nice to have an icon against apps to show the SharedUserID status.
