### ISSUE TITLE
[BUG] Missing App Icons

### ISSUE THREAD

**Issue by TheMysticS** [d4rken/mystic-permissions#23]
Icons for some apps are missing:

![Screenshot_2022-07-17-20-32-57-52_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179404382-6c04608d-d793-4a73-ada6-f149901f3ffd.jpg)

![Screenshot_2022-07-17-20-33-27-54_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179404383-319e65c6-e8f6-4ca9-abd8-345b7b04a1b2.jpg)

**Comment by d4rken** [comment]
Did you need to scroll quickly or something else to reproduce?

**Comment by TheMysticS** [comment]
No, the icons are just missing now.

Fx app whose icon is missing is installed in the Work Profile. But this problem isn't there for other apps in the Work Profile.

In the 2nd screenshot, Amazon Shopping app is listed, but I have not installed that app. Likewise, I just checked under Settings/ Apps, none of those OnePlus apps are showing up either.

**Comment by d4rken** [comment]
> No, the icons are just missing now.

If you click to details, does it show there?

> Fx app whose icon is missing is installed in the Work Profile. But this problem isn't there for other apps in the Work Profile.

Ok, just a coincidence then? I need to setup a workprofile on my device to test.

> In the 2nd screenshot, Amazon Shopping app is listed, but I have not installed that app. Likewise, I just checked under Settings/ Apps

I only see the MP3 app, not the shopping app?

> none of those OnePlus apps are showing up either.

The system does not list everything, especially installed packages that are not full fledged apps (e.g. icon packs on your screenshot).
SD Maid will probably be able to show them too.

The icon packs probably don't have an icon? What icon does SD Maid show for them?

**Comment by TheMysticS** [comment]
It is blank on the App Details screen too:

![Screenshot_2022-07-17-21-34-18-21_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179409895-aab47c4a-52f4-4ae1-a4e3-6bb70cf66bcd.jpg)

SD Maid shows the icon properly:

![Screenshot_2022-07-17-21-25-00-45_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/54448474/179410016-9e1214d9-cab8-4646-992e-1e18b6478136.jpg)

I have the Amazon Music and Prime Video apps installed. Only the Shopping app is not installed.

As with the OnePlus apps, SD Maid shows the generic Android icons for all the ones shown in OP.

**Comment by dragonGod97677** [comment]
This happened to me but only for 400ms-800ms~, tested by doing fast scrolling, tap to a app and return to previous screen quickly, search for a app and tap to a app and return to previous screen quickly.

**Comment by d4rken** [comment]
Except for not supporting icons from work-profiles, I think I fixed the icon loading with.
c5551253f7b35b572e9a2975f901fd6c025ad9ca
Check after next release.
