### ISSUE TITLE
Extra build variants (GPlay?FOSS?)

### ISSUE THREAD

**Issue by IzzySoft** [d4rken/mystic-permissions#4]
Hi @d4rken, I just wonder as my library scanner reports Bugsnag: is it opt-in, so I can override the `Tracking` marker for your app?

**Comment by d4rken** [comment]
Hey how are you ☺️. Are looking to setup FDroid?

BugSnag SDK is currently just in there as it's part of my starter project, can't actually be enabled by the user atm (backend isn't setup).

Could maybe remove it.

Depends a bit on how popular this becomes.
If there is enough demand, I could release a donation version on Google Play, which would then warrant setting up BugSnag and hiring a designer for an app icon 😅.

Maybe a Build Variant for Google Play? With IAP and BugSnag, and a FOSS variant without? 🤔

**Comment by d4rken** [comment]
Yeah you can remove the tag, I'll make it opt-in or move it to an extra build variant all together before setting it up.

> Sounds good to me! If you attach both APKs to releases, please let me know in advance so we can define which APK I can pick for my repo. And once you feel the app ready/mature enough for F-Droid.org, I can help with that as well.

I'll keep the APKs on GitHub as is, and if there is a Google Play variant it will have to be APK bundles anyways and that's probably uninteresting to everyone but Google Play :sweat: 

> And once you feel the app ready/mature enough for F-Droid.org, I can help with that as well.

Awesome, give me a few more days :wink:

**Comment by IzzySoft** [comment]
Great, thanks! So the (only) APK attached here will be the one without Bugsnag then?

> Awesome, give me a few more days

All the time you need. Your app is already available via my repo, so no need to hurry. Better start at F-Droid.org with something "mature" – "first impression" and all that :wink:

**Comment by d4rken** [comment]
Created another build flavor, kept bugsnag in both.
Made the reporting opt-in for the github build and opt-out for gplay.
(Bugsnag is still not setup though until I actually do a Google Play release).

Relevant code for opt-in/out:
https://github.com/d4rken/mystic-permissions/blob/eea45b80655eeeded9d9a450514b26bcf95bb226/app/src/main/java/eu/darken/myperm/common/debug/autoreport/DebugSettings.kt#L19-L23

I added gplay billing dependency but it should only be included in the gplay buid. For the foss build it just links to GitHub.

There should still only be one APK attached to releases, but the name has slightly changed, e.g.:
`eu.darken.myperm-v0.0.5(500)-FOSS-RELEASE-ea3d2e5.apk`
does that matter?

**Comment by IzzySoft** [comment]
> Made the reporting opt-in for the github build and opt-out for gplay.

Sounds fine with me – so I can keep the `Tracking` AF out (will white-list Bugsnag for your app then)

> I added gplay billing dependency but it should only be included in the gplay buid. For the foss build it just links to GitHub.

Again fine, thanks! TBH I do not care too much what you put into the Play build¹ as long as it does not hit the Foss build.

> There should still only be one APK attached to releases, but the name has slightly changed

The name only matters if there are multiple APKs attached – because then I need to take care the updater does not pick the wrong one.

So thanks a lot – that's a very good solution for all involved!

----

¹ <sub>well, to a degree: would you add a bunch of invasive trackers, users might get curious whether they could really trust the Foss one or if something sneaked in there, too :rofl:</sub>

**Comment by IzzySoft** [comment]
PS: You forgot to attach the APK to the latest release :scream:

**Comment by d4rken** [comment]
> PS: You forgot to attach the APK to the latest release scream

Ahhh thanks.

https://github.com/d4rken/mystic-permissions/commit/b10c120e5eb7748b83898ce1135cd8200dbea860#diff-1a01768048176e9aae1daf1472171fd9134e697c1ed988f40d12370a483cd3ecR64

**Comment by IzzySoft** [comment]
Gladly – and thanks to you! I just triggered the updater manually – fetched the update fine, so all seems set. Just an icon is not there (ah, yes, issue is already open for that I see).

As for metadata in general: would you like a PR shipping you initial [fastlane structures](https://gitlab.com/-/snippets/1895688)? I could offer to send you what I've set up with my repo currently – so you could take over from there and adjust whenever needed. And build upon – e.g. adding screenshots, icon, featureGraphic :wink:

**Comment by IzzySoft** [comment]
No build services here – and yes, redirects should work (at least for a while). If you can provide me a list of packageIds I should check, I can take care to update the URLs so everything is straight again.

Speaking of permissions and the current GH/MS controversy: should you move to Codeberg, just let me know. There are no forwards from here to there – but my updater of course can deal with Codeberg just fine (I've moved almost all of my repos there years ago and archived them here). And yes, you have orgs there as well as CI and pages :wink:

**Comment by IzzySoft** [comment]
> What packageIds do you mean?

Quick check: I can find `eu.darken.bluemusic`, ` eu.darken.myperm`, ` eu.thedarken.rootvalidator` and  `eu.thedarken.wldonate` in my repo (links for ` eu.darken.myperm` adjusted now).

> Not sure I would go with Codeberg over Gitlab though

Codeberg is hosted in DE and is driven by a community (Codeberg e.V.) – both strong reasons for me. They have very good support – another strong argument. Also, migration works like a breeze. That I also have contact to some of the team is a bonus to me – but I very much like how it works. Well, just saying :wink:

**Comment by d4rken** [comment]
Is there a better crash tracking tool that wouldn't get tagged as `Tracking` when made opt-out?

**Comment by IzzySoft** [comment]
Afraid not. It needs to be marked a false positive when it's opt-in. But be welcome to check [potential candidates](https://gitlab.com/-/snippets/1896503#firebase-per-se) for "better otherwise" :wink:

**Comment by IzzySoft** [comment]
PS: your Readme has an PlayStore link that leads to a 404 – but no link to the alreay working representation in my repo. Mind to fix that? You know ehre to [find a badge for that](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it), right? :wink:

And while on it: you could move that app banner to `/fastlane/metadata/android/en-US/images/featureGraphic.png` and place an `icon.png` next to it. I just picked the two manually – but if they were in Fastlane, my updater could take care for them automatically.

**Comment by d4rken** [comment]
> PS: your Readme has an PlayStore link that leads to a 404 – but no link to the alreay working representation in my repo. Mind to fix that?

Google has rejected the APK, need to submit it for review again.

> You know ehre to [find a badge for that](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it), right? wink

I'm a bit confused on the different between yoru repos and F-Droid, could you elaborate?

> And while on it: you could move that app banner to /fastlane/metadata/android/en-US/images/featureGraphic.png and place an icon.png next to it. I just picked the two manually – but if they were in Fastlane, my updater could take care for them automatically.

Good point, will do.

**Comment by IzzySoft** [comment]
> Google has rejected the APK, need to submit it for review again.

Ah, the usual G-hell… :cry:

> I'm a bit confused on the different between yoru repos and F-Droid, could you elaborate?

Basically [this](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ). Plus that F-Droid's inclusion criteria are stricter.

Thanks for moving icon+featureGraphic to Fastlane – adjusted the config for my updater to check them on updates.

**Comment by d4rken** [comment]
The badge doesn't fit nicely into the readme's current style, (or we get a matching badge for google play and github too) but I'm open to adding a bullet point to the download section.

Something like

* Available for F-Droid via IzzyOnDroid repository

What happens when it is clicked? The F-droid app on the users phone opens?

**Comment by IzzySoft** [comment]
> The badge doesn't fit nicely into the readme's current style

Look more closely – and pick "the other one" which fits perfectly in the row between "release" and "downloads" :wink: <img src="https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/com.mirfatif.permissionmanagerx&label=IzzyOnDroid&cacheSeconds=86400"> Details on how to use that one [are here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/API). Further down you could then place a text link next to the others (or use the corresponding badges there for each of them: there's one for Google, and another for Github available, so the 3 would look similar in style to each other).

[<img src="https://raw.githubusercontent.com/deckerst/common/main/assets/get-it-on-github.png" height="100">](https://raw.githubusercontent.com/deckerst/common/main/assets/get-it-on-github.png) [<img src="https://user-images.githubusercontent.com/6781438/181350360-c1b47685-e91e-4096-b88f-72d2c27e32de.png" height="100">](https://user-images.githubusercontent.com/6781438/181350360-c1b47685-e91e-4096-b88f-72d2c27e32de.png) [<img src="https://camo.githubusercontent.com/68b69c9e16ee529bdd2540b7f7033afc8de0535966d2c36ee3878410f799f270/68747470733a2f2f706c61792e676f6f676c652e636f6d2f696e746c2f656e5f75732f6261646765732f696d616765732f67656e657269632f656e2d706c61792d62616467652e706e67" height="100">](https://camo.githubusercontent.com/68b69c9e16ee529bdd2540b7f7033afc8de0535966d2c36ee3878410f799f270/68747470733a2f2f706c61792e676f6f676c652e636f6d2f696e746c2f656e5f75732f6261646765732f696d616765732f67656e657269632f656e2d706c61792d62616467652e706e67)

(I've just picked them from different locations – you may wish to copy them and keep them in your repo so they do not disappear)

> What happens when it is clicked? The F-droid app on the users phone opens?

If you link it directly to the app details page, it will open in a browser. But you can use a slightly different URL: using `https://apt.izzysoft.de/packages/eu.darken.myperm/`, on the desktop it will be opened in the web browser (and redirected accordingly) – while on an Android device with the F-Droid app installed, the user will be prompted to choose between browser and F-Droid app.

**Comment by d4rken** [comment]
> Look more closely – and pick "the other one" which fits perfectly in the row between "release" and "downloads" 

Yeah but that doesn't fit there, it's more for "look but not touch". The small badges do not present themselves to users as a primary way to download the app, especially when having 3 badges for 3 download places there :thinking:

**Comment by d4rken** [comment]
Maybe like this
https://github.com/d4rken-org/permission-pilot/blob/main/README.md#downloads

**Comment by IzzySoft** [comment]
That looks fine! And even gives additional details. Cool!
