### ISSUE TITLE
Detection & filter for side-loaded apps

### ISSUE THREAD

**Issue by d4rken** [d4rken/mystic-permissions#5]
From https://github.com/d4rken/mystic-permissions/issues/1#issuecomment-1186192801

See for installer packagenames: https://github.com/d4rken/sdmaid-public/issues/5618

/cc @TheMysticS

**Comment by d4rken** [comment]
Basic detection (Google Play or not) is available since https://github.com/d4rken/mystic-permissions/releases/tag/v0.0.7

**Comment by dragonGod97677** [comment]
vivo app store: `com.vivo.appstore`
oppo app store: `com.oppo.market`
Huawei app store: `com.huawei.appmarket`
Samsung app store: `com.huawei.appmarket`

**Comment by dragonGod97677** [comment]
Hmm the app also detected that i installed this app via PC adb.
![Screenshot_2022-07-17-23-59-03-90](https://user-images.githubusercontent.com/38875906/179413083-d606b220-c309-40e0-83fd-05d8f46ffa6f.png)
This should renamed to "App installed via PC, Android Debug Bridge" or just "App installed via ADB

**Comment by d4rken** [comment]
Is that the official label? Do you have a link to documentation that says this?

**Comment by dragonGod97677** [comment]
> Is that the official label? Do you have a link to documentation that says this?

This is the [Code](https://github.com/d4rken/mystic-permissions/blob/3c5352b9aeac1cb4308658a9018ce5c69f1aded0/app/src/main/java/eu/darken/myperm/apps/core/InstallerInfo.kt) you use to determine from what source the app installed right? Well i dont know if that's the official label when you install an app via adb (i think maybe this is different on other Android version?)

and other app manager seems catches it too and adds label "pc"
![Screenshot_2022-07-18-00-56-18-57](https://user-images.githubusercontent.com/38875906/179416421-a4e36fde-5a6d-4fed-b0c8-8109d42e858b.png)

**Comment by dragonGod97677** [comment]
[Documentation](https://developer.android.com/reference/kotlin/android/content/pm/InstallSourceInfo) 
![Screenshot_2022-07-18-01-14-45-19](https://user-images.githubusercontent.com/38875906/179417099-cbd25ff1-ffb6-424a-a970-d44f285a2dbb.png)

**Comment by d4rken** [comment]
AFAIK installing via ADB does not automatically set a value, but it is `null` instead.
For your app, the name was set to `pc` by the installer, though I don't it was ADB, unless you added the option to set it like then when executing the `adb install` command.

I think the label here should be a default "Unknown installer (pc)".

> This is the [Code](https://github.com/d4rken/mystic-permissions/blob/3c5352b9aeac1cb4308658a9018ce5c69f1aded0/app/src/main/java/eu/darken/myperm/apps/core/InstallerInfo.kt) you use to determine from what source the app installed right? Well i dont know if that's the official label when you install an app via adb (i think maybe this is different on other Android version?)

This is a container class to later allow me to add more information easily. The detection itself currently happens here:

https://github.com/d4rken/mystic-permissions/blob/3c5352b9aeac1cb4308658a9018ce5c69f1aded0/app/src/main/java/eu/darken/myperm/apps/core/AppRepo.kt#L88-L117

PS:(Remove the `!` from screenshots when not strictly necessary, to keep the thread easily scrollable.

**Comment by d4rken** [comment]
> vivo app store: `com.vivo.appstore` oppo app store: `com.oppo.market` Huawei app store: `com.huawei.appmarket` Samsung app store: `com.sec.android.app.samsungapps` Xiaomi app store: `com.xiaomi.mipicks`

I've added these, see:
https://github.com/d4rken/mystic-permissions/blob/c5551253f7b35b572e9a2975f901fd6c025ad9ca/app/src/main/java/eu/darken/myperm/apps/core/known/ZKnownPkgs.kt#L14-L40

**Comment by d4rken** [comment]
If sideloading detection itself is working ok, please close this, and for adding new app stores, we can make new tickets.

**Comment by dragonGod97677** [comment]
> If sideloading detection itself is working ok, please close this, and for adding new app stores, we can make new tickets.

Uh, you are the one created this XD

**Comment by dragonGod97677** [comment]
> PS:(Remove the `!` from screenshots when not strictly necessary, to keep the thread easily scrollable.

Okay, sure 👍
